import Head from 'next/head'
import { Inter } from 'next/font/google'
import AppLayout from '@/components/AppLayout/AppLayout'
import { Button, Title } from '@mantine/core'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>EasyCake App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Title>
          EasyCake Test
        </Title>
        <Button>
          Click Me!
        </Button>
      </AppLayout>
    </>
  )
}
